<?php
return array (
  'quick_donation_page' => array(
    'group_name' => 'Quick Donation',
    'group' => 'quickdonate',
    'name' => 'quick_donation_page',
    'prefetch' => 0,
    'type' => 'Integer',
    'quick_form_type' => 'Element',
    'html_type' => 'Select',
    'default' => null,
    'default' => NULL,
    'add' => '4.5',
    'title' => 'Quick Donation Page',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Contribution Page ID for Donation form',
    'help_text' => null,
  ),
  'ziptastic_enable' => array(
    'group_name' => 'Quick Donation',
    'group' => 'quickdonate',
    'name' => 'ziptastic_enable',
    'prefetch' => 0,
    'type' => 'Integer',
    'quick_form_type' => 'Element',
    'html_type' => 'Checkbox',
    'default' => 0,
    'add' => '4.5',
    'title' => 'Ziptastic Enabled',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Ziptastic enable for Donation form',
    'help_text' => null,
  ),
);
